### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by luvchurchill** [alioguzhan/dobby#5]
after running configure (in ubuntu)

`configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."`

**Comment by alioguzhan** [comment]
Hmm. Looks like a missing tool or lib. Can you try this inside the project folder:

```sh
sudo apt install autoconf automake
autoreconf -i 
```

Then try to run `configure and other things` to install:

```sh
./configure
make
make install
```

**Comment by luvchurchill** [comment]
that fixed it! thanks.
